name: 'Build And Publish Images'
description: 'Builds and publishes images with pack'
inputs:
  version:
    description: 'dataflow version'
    required: true
  dockerhub-username:
    description: 'dockerhub username'
    required: true
  dockerhub-password:
    description: 'dockerhub password'
    required: true
runs:
  using: "composite"
  steps:
  - name: Install pack
    uses: jvalkeal/build-zoo-handler@v0.0.4
    with:
      pack-version: 0.24.1
  - name: Build Images
    env:
      TAG: ${{ inputs.version }}
    shell: bash
    run: .github/actions/build-images/pack-images.sh

  # docker hub login
  - uses: docker/login-action@v1
    with:
      username: ${{ inputs.dockerhub-username }}
      password: ${{ inputs.dockerhub-password }}

  # push images
  - name: Push images
    env:
      TAG: ${{ inputs.version }}
    shell: bash
    run: |
      DEFAULT_JDK=11
      docker tag springcloud/spring-cloud-dataflow-server:$TAG-jdk$DEFAULT_JDK springcloud/spring-cloud-dataflow-server:$TAG
      docker tag springcloud/spring-cloud-dataflow-composed-task-runner:$TAG-jdk$DEFAULT_JDK springcloud/spring-cloud-dataflow-composed-task-runner:$TAG
      docker tag springcloud/spring-cloud-dataflow-tasklauncher-sink-kafka:$TAG-jdk$DEFAULT_JDK springcloud/spring-cloud-dataflow-tasklauncher-sink-kafka:$TAG
      docker tag springcloud/spring-cloud-dataflow-tasklauncher-sink-rabbit:$TAG-jdk$DEFAULT_JDK springcloud/spring-cloud-dataflow-tasklauncher-sink-rabbit:$TAG
      docker tag springcloud/spring-cloud-dataflow-single-step-batch-job:$TAG-jdk$DEFAULT_JDK springcloud/spring-cloud-dataflow-single-step-batch-job:$TAG
      for v in 8 11 17
      do
        docker push springcloud/spring-cloud-dataflow-server:$TAG-jdk$v
        docker push springcloud/spring-cloud-dataflow-composed-task-runner:$TAG-jdk$v
        docker push springcloud/spring-cloud-dataflow-tasklauncher-sink-kafka:$TAG-jdk$v
        docker push springcloud/spring-cloud-dataflow-tasklauncher-sink-rabbit:$TAG-jdk$v
        docker push springcloud/spring-cloud-dataflow-single-step-batch-job:$TAG-jdk$v
      done
      docker push springcloud/spring-cloud-dataflow-server:$TAG
      docker push springcloud/spring-cloud-dataflow-composed-task-runner:$TAG
      docker push springcloud/spring-cloud-dataflow-tasklauncher-sink-kafka:$TAG
      docker push springcloud/spring-cloud-dataflow-tasklauncher-sink-rabbit:$TAG
      docker push springcloud/spring-cloud-dataflow-single-step-batch-job:$TAG

  # build/publish support images
  - name: Publish Grafana Prometheus
    uses: docker/build-push-action@v2
    with:
      context: src/grafana/prometheus/docker/grafana
      push: true
      tags: springcloud/spring-cloud-dataflow-grafana-prometheus:${{ inputs.version }}
  - name: Publish Grafana InfluxDB
    uses: docker/build-push-action@v2
    with:
      context: src/grafana/influxdb/docker/grafana
      push: true
      tags: springcloud/spring-cloud-dataflow-grafana-influxdb:${{ inputs.version }}
  - name: Publish Prometheus Local
    uses: docker/build-push-action@v2
    with:
      context: src/grafana/prometheus/docker/prometheus-local
      push: true
      tags: springcloud/spring-cloud-dataflow-prometheus-local:${{ inputs.version }}
