name: Publish Bundle
description: Publish Bundle
inputs:
  path:
    description: path to bundle files
    required: true
  repository:
    description: repository to publish
    required: true
  version:
    description: semver version
    required: true
  
runs:
  using: "composite"
  steps:
  - name: Setup Envs
    shell: bash
    run: |
      echo RTAG=R$(date +%y%m%d%s%N) >> $GITHUB_ENV
  - name: Tanzu Dance
    id: tanzu-dance
    env:
      BUNDLE_PATH: ${{ inputs.path }}
      REPOSITORY: ${{ inputs.repository }}
      VERSION: ${{ inputs.version }}
    shell: bash
    run: |
      if [ "$USE_SRP" == "true" ]; then
        if [ "$SRP_SCRIPTS" == "" ]; then
          echo "SRP_SCRIPTS not defined"
          exit 2
        fi
        if [[ "$REPOSITORY" == *"-package"* ]]; then
          export OBSERVATION=package-publish
        else
          export OBSERVATION=repository-publish
        fi
        export OUTPUT_VERSION=$VERSION
        $SRP_SCRIPTS/run-under-observer.sh bash "${{ github.action_path }}/publish-bundle.sh"
      else
        bash "${{ github.action_path }}/publish-bundle.sh"
      fi
