name: CI Carvel

on:
  push:
    branches:
      - main
    paths:
      - 'src/carvel/**'
  workflow_dispatch:

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/carvel
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - name: Setup npm
      run: |
        npm ci
    - name: Lint
      run: |
        npm run format-check
    - name: Test
      run: |
        npm test
